BASE_URL:       https://mentor-dev.cdsvisual.net
BASE_URL2:       https://vfm-dev.cdsvisual.net
ProcedureId:    1bedc91b-23b1-4493-a351-999e040beace   #7d84ffe5-024f-4066-8752-714dcf7e784c
FolderID:    43eaf07a-838e-440f-a4ab-14d7f47eccb5
ProcedureToDelete:    d513efec-14ea-4e87-a2fc-40affb3513a8
detailsProcedureId:     11673c3a-62c5-40b2-82fc-2654935899ef
WI_ID:           e3dc71e0-10ea-4a8e-9258-19612821ea45
AUTHOR1_EMAIL:  autoauthora1@mailinator.com
AUTH_TOKEN:
AUTH_TOKEN_SiteAdm:
AUTH_TOKEN_OrgAdm: